### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by desu2desu** [erwinkramer/SoundCloud-Playlist-Sync#17]
sync-able favorites list / sync on program start
Creating the manifest in the artist folder
Drop-down history for the soundcloud URL and local directory boxes.
Option to turn off the creation of playlist files.

**Comment by erwinkramer** [comment]
Hi @desu2desu, thanks for bringing out some ideas, here's my look at each suggestion:

> sync-able favorites list / sync on program start

Sync on program start is a good suggestion. Not sure what you mean by sync-able favorites list because favorites are sync-able? 

> Creating the manifest in the artist folder

You mean 1 manifest per artist? It makes things elegant i guess, but maybe too complex for the benefits. Why would you want it? 

> Drop-down history for the soundcloud URL and local directory boxes.

Good suggestion.

> Option to turn off the creation of playlist files.

Good suggestion and easy to implement, i guess i'll do this pretty soon.

**Comment by desu2desu** [comment]
To clarify about the favorites list, I mean a list of soundcloud profile urls to sync the tracks of many artists instead of doing it one at a time.


> You mean 1 manifest per artist? It makes things elegant i guess, but maybe too complex for the benefits. Why would you want it?

I want the manifest thing because it would stop the change settings or directory thing if you have a manifest of another artist/playlist in the same folder you're trying to download into. Ex:
![manifest](https://cloud.githubusercontent.com/assets/26392214/23970587/e10c2fb6-098f-11e7-8f6e-d4f458899f94.png)

**Comment by erwinkramer** [comment]
@desu2desu , i implemeted the option to turn off the creation of playlist files.

The updater broke so u have to manually download the new version at https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases/tag/r3.0.0 

New versions will auto update again with this version

**Comment by erwinkramer** [comment]
Hi @desu2desu some progress:

> Creating the manifest in the artist folder

So a new version is up that supports multiple manifest files in the root folder. This solves your problem with another artist/playlist in the same folder. 

I'm not sure why i didn't think of this before because it was just a slight modification. However, you should be cautious when syncing more than one sync configuration in the same folder. If both configurations have the same songs (in a playlist or favorites list) and you use two-way sync then removal of a song in SoundCloud in 1 sync configuration will remove the other if it occurred in the other sync configuration as well. 

Also playlist file generation is still done on root level and only for one sync configuration, so this as well is not functioning well with multiple sync configurations in the same folder.

**Comment by Herkules97** [comment]
Would it be possible to add an option to download the profile's playlists or albums? Record labels usually have a profile with playlists but they don't have the tracks themselves on their own profile, just the playlists and albums to them. 
Another suggestion is to add the ability to download reposts aswell.

**Comment by erwinkramer** [comment]
Hi @desu2desu ,

In the new version (3d24e6221057ca7f475229b57bfaed381b989519) there is support for up to 5 configurations. This eliminates the following requirement: 

> Drop-down history for the soundcloud URL and local directory boxes.

I will close this issue now. If you really want the other 2 suggestions, please open a separate issue per suggestion, that way it's easier to track.
