### ISSUE TITLE
Author's picture/song picture not downloaded

### ISSUE THREAD

**Issue by mistertoze** [erwinkramer/SoundCloud-Playlist-Sync#18]
Hi there,

First of all thank you for continuing this great program.

One thing I noticed is that it no longer downloads and attaches the custom picture (or the author's avatar if no custom picture is used) to the songs like the StephenCasella version did.

I kinda liked that feature.

**Comment by mcprat** [comment]
hmm...it should be...I still see album art. Maybe it is under a different metadata tag or something. What program do you use to listen to your tracks?

**Comment by erwinkramer** [comment]
Hi @mistertoze,

Could you please provide some track URLs that aren't showing track art?

**Comment by mistertoze** [comment]
Uhhh... all of them? I just started using this version today to backup my playlists and none of the mp3 have album art.

Am I doing something wrong then?

**Comment by erwinkramer** [comment]
If you could be more specific on what songs you downloaded and what program you use to view the album art then I could reproduce the issue, if I can't reproduce it I can't solve it

**Comment by mistertoze** [comment]
I can see the album art of all songs downloaded with the older version, on explorer and windows media player.

But it seems to be missing from every file downloaded with this new version.

My configuration is:
- All songs from this playlist URL
- One-way sync
- Chose high quality versions if available (convert high-quality to mp3)
- Include artist name in filename
- Replace illegal characters
- Generate playlists
- Concurrency: 1

You can use this song as an example: https://soundcloud.com/triplekyu/nuclearman

Thanks for your time.

**Comment by erwinkramer** [comment]
Thanks for the info, that's helpful. I'll be looking into it this week.

**Comment by mcprat** [comment]
I believe he is right. I have tracks last modified on 5/16/16 and earlier where I can view the album art in Windows Explorer after turning thumbnails on everywhere. I have tracks last modified on 5/17/16 where I cannot. Whatever change you made to the program on that day must have affected how the album art is tagged somehow...

I have never noticed this problem because I can still see the album art in Foobar2000 for every single one of my tracks for some reason.... (I strongly recommend getting Foobar btw. Many many leagues ahead of WMP)

**Comment by erwinkramer** [comment]
Hi @mistertoze , i fixed the issue. Pictures weren't showing in Windows Explorer and WMP because i reverted back to the id3v2.2 standard of metadata tagging, i did this to be really safe from compatibility issues i had with id3v2.4. I now switched to id3v2.3 and it's working again. Please update the app and redownload any files you want to have it working properly on. 

Just so you know, the album art actually IS in the file, like @mpratt14 noticed. It's just that some apps fail to display it.

**Comment by mistertoze** [comment]
Thanks! It's working great now!
But I did find another unrelated bug (sorry!).
I'll make a new thread about it.
